FROM arm32v7/debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    autoconf \
    automake \
    libtool \
    pkg-config \
    libasound2-dev \
    libfftw3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
